version: '3.7'
services:
  backend:
    image: ghcr.io/suprincesu/test-server-ghcr:latest
    env_file:
      - .env
    ports:
      - 8004:8004
    volumes:
      - ./public:/app/public
    restart: on-failure
